---
title: "Multiple Linear Regression (Estimation and Inference)"
author: "Blake Pappas"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  pdf_document:
    toc: false
    toc_depth: 3
    fig_width: 8.5
    fig_height: 6.5
    fig_caption: yes
header-includes:
   - \usepackage{animate}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Species Diversity on the Galapagos Islands

### First Step: Load the Data

```{r, warning = FALSE}
# install.packages("faraway")
library(faraway)
data(gala)
head(gala)
```

### Plot the Pairwise Scatterplots

```{r, warning = FALSE}
pairs(gala[, -2], cex = 0.95, col = "blue", las = 1)
library(ggplot2)
library(GGally)
ggpairs(gala[, -2])
```

### Correlation Matrix

```{r}
cor(gala[, -2])
```

### Model 1: Fitting a Simple Linear Regression

Here we use *Elevation* as the predictor as it has the highest correlation with *Species*.

```{r}
M1 <- lm(Species ~ Elevation, data = gala)
summary(M1)

plot(gala$Elevation, gala$Species, xlab = "Elevation (m)", ylab = "Number of Plant Species",
     las = 1, pch = 16, col = "blue")
abline(M1)
```

### Model 2: Adding *Area*

```{r, message = FALSE, warning = FALSE}
M2 <- lm(Species ~ Elevation + Area, data = gala)
summary(M2)

Elevation_grid <- seq(0, 1750, 10)
Area_grid <- seq(0, 4700, 10)
temp <- expand.grid(Elevation_grid, Area_grid)
x_new <- data.frame(Elevation = temp$Var1, Area = temp$Var2)

y_pred <- matrix(predict(M2, x_new), nrow = length(Elevation_grid))

library(plot3D)

# Fitted Points for Droplines to Surface
fitpoints <- predict(M2)

# Scatterplot with Regression Plane
scatter3D(gala$Elevation, gala$Elevation, gala$Species,
          pch = 16, cex = 0.6, theta = 20, phi = 30,
          ticktype = "detailed",
          xlab = "Elevation", ylab = "Area", zlab = "Species",
          surf = list(x = Elevation_grid, y = Area_grid,
                      z = y_pred, facets = NA, fit = fitpoints))

library(fields)
image.plot(Elevation_grid, Area_grid,  y_pred, las = 1,
           xlab = "Elevation (m)", ylab = expression(paste("Area (", km^2, ")")))
```

### Model 3: Adding *Adjacent*

```{r}
M3 <- lm(Species ~ Elevation + Area + Adjacent, data = gala)
summary(M3)
```

### Full Model

```{r}
M4 <- lm(Species ~ Elevation + Area + Adjacent + Nearest + Scruz, data = gala)

gala2 <- gala[, -2]
M4_2 <- lm(Species ~ ., data = gala2) # . means select all
summary(M4_2)

summary(M4)
predict(M4)
confint(M4)
```

### Parameter Estimation

```{r}
X <- model.matrix(M4)
y <- gala$Species

# Regression Parameters
(beta_hat <- solve(t(X) %*% X) %*% t(X) %*% y) # t(X) means transpose
beta_hat_faster <- solve(crossprod(X), crossprod(X, y))

# Fitted Values
(y_hat <- X %*% solve(t(X) %*% X) %*% t(X) %*% y)
```

### ANOVA

```{r}
anova(M4)
```


## Simulation

### $R^2$ vs. $R^{2}_{adj}$

```{r}
set.seed(123)
N = 500
x1 <- replicate(N, rnorm(30))
x2 <- replicate(N, rnorm(30))
y1 <- apply(x1, 2, function(x) 5 + 2 * x + rnorm(30, 0, 1))
R.sq <- array(dim = c(N, 4))
for (i in 1:N) {
  R.sq[i, 1] = summary(lm(y1[, i] ~ x1[, i]))$r.squared
  R.sq[i, 2] = summary(lm(y1[, i] ~ x1[, i]))$adj.r.squared
  R.sq[i, 3] = summary(lm(y1[, i] ~ x1[, i] + x2[, i]))$r.squared
  R.sq[i, 4] = summary(lm(y1[, i] ~ x1[, i] + x2[, i]))$adj.r.squared
}

par(mfrow = c(1, 2))
plot(R.sq[, 1], R.sq[, 3], pch = 16, cex = 0.65, col = "blue",
     xlab = expression(paste("Model 1: ", R^2)),
     ylab = expression(paste("Model 2: ", R^2)))
abline(0, 1)

boxplot(R.sq[, 3] - R.sq[, 1], las = 1, xlab = expression(paste(R^2, " Model 2 - Model 1")))
abline(h = 0, lty = 2, col = "red")

par(las = 1, mfrow = c(1, 2), mar = c(5.1, 4.6, 1.1, 1.1))
plot(R.sq[, 2], R.sq[, 4], pch = 16, cex = 0.5, col = "blue",
     xlab = expression(paste("Model 1: ", R[adj]^2)),
     ylab = expression(paste("Model 2: ", R[adj]^2)))
abline(0, 1)

boxplot(R.sq[, 4] - R.sq[, 2], las = 1, xlab = expression(paste(R[adj]^2, " Model 2 - Model 1")))
abline(h = 0, lty = 2, col = "red")
```