---
title: "Clustering Analysis"
author: "Blake Pappas"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  pdf_document:
    toc: false
    toc_depth: 3
    fig_width: 6
    fig_height: 5
    fig_caption: yes
header-includes:
   - \usepackage{animate}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## K-Means Clustering

### Simulated Example

```{r, warning = FALSE}
set.seed(101)
library(scales)
x <- matrix(rnorm(100 * 2), 100, 2)
xmean <- matrix(rnorm(8, sd = 4), 4, 2)
which <- sample(1:4, 100, replace = TRUE)
x = x + xmean[which, ]
plot(x, col = which, pch = 19, xlab = expression(X[1]),
     ylab = expression(X[2]), las = 1)
grid()

# K-Means Clustering
km.out <- kmeans(x, 4)
km.out
table(which, km.out$cluster)
id2 <- which(km.out$cluster == 2)
id4 <- which(km.out$cluster == 4)
km.out$cluster[id2] <- 4
km.out$cluster[id4] <- 2
table(which, km.out$cluster)
plot(x, col = km.out$cluster, cex = 2, pch = 1, lwd = 2,
     xlab = expression(X[1]), ylab = expression(X[2]), las = 1)
points(x, col = which, pch = 19)
```

### Geyser Example

```{r}
# Clustered Scatterplots
km3.faithful <- kmeans(faithful, 3)
km2.faithful <- kmeans(faithful, 2)
km4.faithful <- kmeans(faithful, 4)

par(las = 1, mfrow = c(1, 3))
plot(faithful, col = km2.faithful$cluster, cex = 0.5, main = "K = 2")
points(km2.faithful$centers, cex = 3, pch = "*", col = 1:2)
grid()
plot(faithful, col = km3.faithful$cluster, cex = 0.5, main = "K = 3")
points(km3.faithful$centers, cex = 3, pch = "*", col = 1:3)
grid()
plot(faithful, col = km4.faithful$cluster, cex = 0.5, main = "K = 4")
grid()
points(km4.faithful$centers, cex = 3, pch = "*", col = 1:4)
```

### US State Facts and Figures Example

```{r warning = FALSE}
# Look at State Data
vars <- c("Income", "Illiteracy", "Life Exp", "HS Grad")
head(state.x77[, vars])

# Fit k Means for k = 2, ..., 10 (Raw Data)
kmlist <- vector("list", 9)
for(k in 2:10) {
  set.seed(1)
  kmlist[[k - 1]] <- kmeans(state.x77[, vars], k, nstart = 5000)
}
# Scree Plot (Raw Data)
tot.withinss <- sapply(kmlist, function(x) x$tot.withinss)
plot(2:10, tot.withinss / kmlist[[1]]$totss, type = "b", xlab = "# Clusters",
     ylab = "SSW / SST", main = "Scree Plot: Raw Data")

# Plot Results (Raw Data)
library(maps)
library(RColorBrewer)
par(mfrow = c(2, 2))
for(k in 3:6) {
  map(database = "state")
  title(paste0("K = ", k, " Clusters: Raw Data"))
  cols <- brewer.pal(k, "Paired")
  for(j in 1:k) {
    ix <- names(which(kmlist[[k - 1]]$cluster == j))
    if(length(ix) > 1) map(database = "state", regions = ix, col = cols[j],
                           fill = T, add = TRUE)
  }
}
```


## Hierarchical Clustering

### US State Facts and Figures Example

```{r}
# Dendrogram Example
apply(state.x77[, vars], 2, mean)
apply(state.x77[, vars], 2, sd)

# Create Distance (Raw and Standardized Data)
distraw <- dist(state.x77[, vars])
diststd <- dist(scale(state.x77[, vars]))

# Hierarchical Clustering (Standardized Data)
hcstdSL <- hclust(diststd, method = "single")
hcstdCL <- hclust(diststd, method = "complete")
hcstdAL <- hclust(diststd, method = "average")

# Plot Results (Standardized Data)
plot(hcstdSL)
plot(hcstdCL)
plot(hcstdAL)
```

## Model-Based Clustering

### Geyser Example

```{r, message = FALSE, warning = FALSE}
library(mclust)
BIC <- mclustBIC(faithful)
model1 <- Mclust(faithful, x = BIC)

plot(model1, what = "classification", cex = 0.5, las = 1)

plot(model1, what = "density", col = "black", lwd = 1.5, las = 1)
points(faithful, col = "blue", cex = 0.5)

# Hypothesis Testing Results
(LRT <- mclustBootstrapLRT(faithful, modelName = "VVV"))
```

### Fisher's Iris Data Example

```{r}
# Scatterplot Matrix
data(iris)
attach(iris) 
iris$Species <- factor(iris$Species)
dat <- iris[, 1:4]
BIC <- mclustBIC(dat)
model2 <- Mclust(dat, x = BIC)

par(las = 1)
plot(model2, what = "classification", cex = 0.5, col = c("green", "blue"))
```