---
title: "Comparisons of Several Mean Vectors"
author: "Blake Pappas"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  pdf_document:
    toc: no
    toc_depth: 3
    fig_width: 6
    fig_height: 5
    fig_caption: yes
  word_document:
    toc: no
    toc_depth: '3'
header-includes: \usepackage{animate}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Swiss Bank Notes Example

### Read the Data

```{r}
dat = read.csv("swiss3.csv", header = FALSE, skip = 1)
```

### Calculate Summary Statistics

```{r}
real <- which(dat$V1 == "real") # Creates a sample for real bank notes
fake <- which(dat$V1 == "fake") # Creates a sample for fake bank notes
(xbar1 <- colMeans(dat[real, -1])) # Computes the mean for the real bank note sample. # The minus 1 excludes the first variable because it is a character data type and not numeric
(xbar2 <- colMeans(dat[fake, -1])) # Computes the mean for the fake bank note sample
(Sigma1 <- cov(dat[real, -1])) # Calculates the covariance matrix for the real bank note sample
(Sigma2 <- cov(dat[fake, -1])) # Calculates the covariance matrix for the fake bank note sample
n1 <- length(real) # Calculates the size of the real bank note sample
n2 <- length(fake) # Calculates the size for the fake bank note sample
p <- dim(dat[, -1])[2] # Calculates the number of variables
Sp <- ((n1 - 1) * Sigma1 + (n2 - 1) * Sigma2) / (n1 + n2 - 2) # Calculates the pooled version of the covariance matrix between the two samples
```

### Perform a Two-Sample Hotelling's T-Square Test

```{r}
# Test Statistic
T.squared <- as.numeric(t(xbar1 - xbar2) %*% solve(Sp * (1 / n1 + 1 / n2)) %*% (xbar1 - xbar2))
Fobs <- T.squared * ((n1 + n2 - p - 1) / ((n1 + n2 - 2) * p)) 

# p-Value
pf(Fobs, p, n1 + n2 - p - 1, lower.tail = F)
```

### Simultaneous Confidence Intervals

```{r}
# Confidence Intervals
s1 <- diag(Sigma1); s2 <- diag(Sigma2)

xbar_diff <- xbar1 - xbar2
sp_diff <- ((n1 - 1) * s1 + (n2 - 1) * s2) / (n1 + n2 - 2)

multipler <- sqrt((p * (n1 + n2 - 2) / (n1 + n2 - p - 1)) * qf(0.95, p, n1 + n2 - p - 1))

sp <- sqrt((1 / n1 + 1 / n2) * sp_diff)

CIs <- cbind(xbar_diff + -1 * multipler * sp, xbar_diff + 1 * multipler * sp)
CIs
```

## MANOVA: Romano-British Pottery Example

```{r}
dat <- read.table("pottery.txt", header = F) # Reads in the table
out <- manova(cbind(V2, V3, V4, V5, V6) ~ V1, data = dat) # Creates the MANOVA table
summary(out) # MANOVA Hypothesis Test
summary(out, test = "Wilks") # Wilks Lambda Hypothesis Test
```